import type { Product, Category, Testimonial, Brand } from "@/types";

export const categories: Category[] = [
  { name: "Men's", slug: "men", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80", count: 42 },
  { name: "Women's", slug: "women", image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&q=80", count: 38 },
  { name: "Kids", slug: "kids", image: "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=400&q=80", count: 24 },
  { name: "Sports", slug: "sports", image: "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=400&q=80", count: 28 },
  { name: "Formal", slug: "formal", image: "https://images.unsplash.com/photo-1614252235316-8c857f38b7f4?w=400&q=80", count: 32 },
  { name: "Casual", slug: "casual", image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&q=80", count: 36 },
];

export const products: Product[] = [
  // ─── #1 Bestseller ───
  {
    _id: "1",
    name: "AirMax Pulse",
    slug: "airmax-pulse",
    description: "Experience next-level comfort with our premium running shoe. Features responsive cushioning and a breathable mesh upper for all-day wear.",
    price: 149.99,
    originalPrice: 189.99,
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80",
    ],
    category: "Running",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: [
      { name: "Red", hex: "#dc2626" },
      { name: "Black", hex: "#171717" },
      { name: "White", hex: "#ffffff" },
    ],
    rating: 4.8,
    reviewCount: 256,
    isNew: true,
    isBestSeller: true,
    inStock: true,
  },
  // ─── #2 Bestseller ───
  {
    _id: "2",
    name: "CloudWalker Pro",
    slug: "cloudwalker-pro",
    description: "Lightweight and stylish, these casual sneakers are perfect for everyday wear. Ultra-soft sole with memory foam insole.",
    price: 89.99,
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80",
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80",
    ],
    category: "Casual",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
    colors: [
      { name: "White", hex: "#ffffff" },
      { name: "Gray", hex: "#6b7280" },
      { name: "Navy", hex: "#1e3a5f" },
    ],
    rating: 4.6,
    reviewCount: 183,
    isNew: true,
    isBestSeller: true,
    inStock: true,
  },
  // ─── #3 Bestseller ───
  {
    _id: "3",
    name: "StrideX Elite",
    slug: "stridex-elite",
    description: "Professional-grade sports shoe designed for peak performance. Carbon fiber plate and advanced grip pattern.",
    price: 199.99,
    originalPrice: 249.99,
    images: [
      "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=600&q=80",
      "https://images.unsplash.com/photo-1579338559194-a162d19bf842?w=600&q=80",
    ],
    category: "Sports",
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: [
      { name: "Blue", hex: "#2563eb" },
      { name: "Black", hex: "#171717" },
      { name: "Orange", hex: "#ea580c" },
    ],
    rating: 4.9,
    reviewCount: 312,
    isNew: true,
    isBestSeller: true,
    inStock: true,
  },
  // ─── #4 ───
  {
    _id: "4",
    name: "Urban Flex",
    slug: "urban-flex",
    description: "Street-ready sneakers with a modern silhouette. Padded collar and cushioned sole for maximum comfort.",
    price: 119.99,
    images: [
      "https://images.unsplash.com/photo-1597045566677-8cf032ed8434?w=600&q=80",
      "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&q=80",
    ],
    category: "Sneakers",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: [
      { name: "White", hex: "#ffffff" },
      { name: "Black", hex: "#171717" },
    ],
    rating: 4.5,
    reviewCount: 147,
    isBestSeller: true,
    inStock: true,
  },
  // ─── #5 ───
  {
    _id: "5",
    name: "TrailBlazer Hiking",
    slug: "trailblazer-hiking",
    description: "Rugged hiking shoe built for tough terrain. Waterproof membrane with reinforced toe cap.",
    price: 169.99,
    originalPrice: 199.99,
    images: [
      "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80",
      "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&q=80",
    ],
    category: "Sports",
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12", "US 13"],
    colors: [
      { name: "Green", hex: "#16a34a" },
      { name: "Brown", hex: "#78350f" },
      { name: "Black", hex: "#171717" },
    ],
    rating: 4.7,
    reviewCount: 98,
    isNew: true,
    isBestSeller: true,
    inStock: true,
  },
  // ─── #6 ───
  {
    _id: "6",
    name: "Velocity Sprint",
    slug: "velocity-sprint",
    description: "Designed for speed. Ultra-lightweight construction with responsive foam technology.",
    price: 134.99,
    images: [
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=80",
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80",
    ],
    category: "Running",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
    colors: [
      { name: "Yellow", hex: "#eab308" },
      { name: "Blue", hex: "#2563eb" },
      { name: "Black", hex: "#171717" },
    ],
    rating: 4.4,
    reviewCount: 76,
    isBestSeller: true,
    inStock: true,
  },
  // ─── #7 ───
  {
    _id: "7",
    name: "Classic Leather",
    slug: "classic-leather",
    description: "Timeless leather sneakers that never go out of style. Premium leather upper with cushioned insole.",
    price: 159.99,
    originalPrice: 189.99,
    images: [
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80",
      "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&q=80",
    ],
    category: "Casual",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: [
      { name: "Brown", hex: "#78350f" },
      { name: "Black", hex: "#171717" },
      { name: "Tan", hex: "#d97706" },
    ],
    rating: 4.7,
    reviewCount: 215,
    isBestSeller: true,
    inStock: true,
  },
  // ─── #8 ───
  {
    _id: "8",
    name: "FlexCore Training",
    slug: "flexcore-training",
    description: "Versatile training shoe for gym and cross-training. Stable base with flexible forefoot.",
    price: 109.99,
    images: [
      "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=600&q=80",
      "https://images.unsplash.com/photo-1543508282-6319a3e2621f?w=600&q=80",
    ],
    category: "Training",
    sizes: ["US 8", "US 9", "US 10", "US 11"],
    colors: [
      { name: "Gray", hex: "#6b7280" },
      { name: "Blue", hex: "#2563eb" },
      { name: "Red", hex: "#dc2626" },
    ],
    rating: 4.3,
    reviewCount: 124,
    isNew: true,
    isBestSeller: true,
    inStock: true,
  },
  // ─── 9 ───
  {
    _id: "9",
    name: "Nova Glide",
    slug: "nova-glide",
    description: "Smooth-gliding running shoes with cloud-like cushioning. Perfect for long distance runners.",
    price: 179.99,
    originalPrice: 219.99,
    images: [
      "https://images.unsplash.com/photo-1579338559194-a162d19bf842?w=600&q=80",
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=80",
    ],
    category: "Running",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: [
      { name: "White", hex: "#ffffff" },
      { name: "Pink", hex: "#ec4899" },
      { name: "Gray", hex: "#6b7280" },
    ],
    rating: 4.6,
    reviewCount: 89,
    isNew: true,
    inStock: true,
  },
  // ─── 10 ───
  {
    _id: "10",
    name: "Metro Walk",
    slug: "metro-walk",
    description: "Everyday walking shoes with superior arch support. Slip-on design with breathable knit upper.",
    price: 79.99,
    images: [
      "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&q=80",
      "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600&q=80",
    ],
    category: "Casual",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: [
      { name: "Navy", hex: "#1e3a5f" },
      { name: "Gray", hex: "#6b7280" },
      { name: "White", hex: "#ffffff" },
    ],
    rating: 4.2,
    reviewCount: 203,
    inStock: true,
  },
  // ─── 11 ───
  {
    _id: "11",
    name: "Apex Elite",
    slug: "apex-elite",
    description: "Premium performance sneaker with advanced energy return system. Designed for athletes.",
    price: 229.99,
    originalPrice: 279.99,
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80",
      "https://images.unsplash.com/photo-1597045566677-8cf032ed8434?w=600&q=80",
    ],
    category: "Sports",
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: [
      { name: "Black", hex: "#171717" },
      { name: "White", hex: "#ffffff" },
      { name: "Gold", hex: "#eab308" },
    ],
    rating: 4.9,
    reviewCount: 178,
    isNew: true,
    inStock: true,
  },
  // ─── 12 ───
  {
    _id: "12",
    name: "Breeze Sandal",
    slug: "breeze-sandal",
    description: "Comfortable sport sandals for warm weather. Adjustable straps with cushioned footbed.",
    price: 59.99,
    images: [
      "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80",
      "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=600&q=80",
    ],
    category: "Casual",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
    colors: [
      { name: "Black", hex: "#171717" },
      { name: "Brown", hex: "#78350f" },
    ],
    rating: 4.1,
    reviewCount: 67,
    inStock: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    name: "Sarah Johnson",
    location: "Los Angeles, CA",
    rating: 5,
    comment: "Absolutely love these shoes! They're perfect for my daily runs. The comfort is unmatched and they still look brand new after months of use.",
    avatar: "https://i.pravatar.cc/80?img=1",
    date: "2 days ago",
    verified: true,
  },
  {
    name: "Mike Chen",
    location: "Singapore",
    rating: 5,
    comment: "Great quality and fast shipping. The size guide was accurate and the shoes fit perfectly. Will definitely be buying more!",
    avatar: "https://i.pravatar.cc/80?img=3",
    date: "1 week ago",
    verified: true,
  },
  {
    name: "Emma Rodriguez",
    location: "Miami, FL",
    rating: 5,
    comment: "I've been wearing these daily for a month and they still look brand new. The comfort level is incredible. Highly recommend to everyone!",
    avatar: "https://i.pravatar.cc/80?img=5",
    date: "3 days ago",
    verified: true,
  },
  {
    name: "James Wilson",
    location: "London, UK",
    rating: 4,
    comment: "The customer service was amazing and the shoes exceeded my expectations. The ordering process was smooth and delivery was prompt.",
    avatar: "https://i.pravatar.cc/80?img=8",
    date: "5 days ago",
    verified: true,
  },
  {
    name: "Priya Patel",
    location: "Mumbai, India",
    rating: 5,
    comment: "Best purchase I've made this year! The shoes are incredibly comfortable and stylish. Received so many compliments already.",
    avatar: "https://i.pravatar.cc/80?img=9",
    date: "1 week ago",
    verified: true,
  },
  {
    name: "Alex Thompson",
    location: "Toronto, Canada",
    rating: 5,
    comment: "Finally found the perfect pair of running shoes. The cushioning is amazing and my feet feel great even after long runs.",
    avatar: "https://i.pravatar.cc/80?img=11",
    date: "2 weeks ago",
    verified: true,
  },
  {
    name: "Sophie Laurent",
    location: "Paris, France",
    rating: 4,
    comment: "Très bien! The quality is outstanding and the design is elegant. Worth every penny. Shipping to France was faster than expected.",
    avatar: "https://i.pravatar.cc/80?img=15",
    date: "3 days ago",
    verified: true,
  },
];

export const brands: Brand[] = [
  { name: "Nike", logo: "https://cdn.simpleicons.org/nike/000", width: 80, height: 40 },
  { name: "Adidas", logo: "https://cdn.simpleicons.org/adidas/000", width: 80, height: 40 },
  { name: "Puma", logo: "https://cdn.simpleicons.org/puma/000", width: 80, height: 40 },
  { name: "Reebok", logo: "https://cdn.simpleicons.org/reebok/000", width: 80, height: 40 },
  { name: "New Balance", logo: "https://cdn.simpleicons.org/newbalance/000", width: 80, height: 40 },
  { name: "Asics", logo: "https://cdn.simpleicons.org/asics/000", width: 80, height: 40 },
  { name: "Skechers", logo: "https://cdn.simpleicons.org/skechers/000", width: 80, height: 40 },
  { name: "Converse", logo: "https://cdn.simpleicons.org/converse/000", width: 80, height: 40 },
];

export const brandLinks: Record<string, string> = {
  "Nike": "https://www.nike.com",
  "Adidas": "https://www.adidas.com",
  "Puma": "https://www.puma.com",
  "Reebok": "https://www.reebok.com",
  "New Balance": "https://www.newbalance.com",
  "Asics": "https://www.asics.com",
  "Skechers": "https://www.skechers.com",
  "Converse": "https://www.converse.com",
};

export const categoryIcons: Record<string, { iconName: string; color: string; hoverColor: string }> = {
  "Men's": { iconName: "User", color: "#F0F4FF", hoverColor: "#2563EB" },
  "Women's": { iconName: "UserRound", color: "#FFF0F5", hoverColor: "#EC4899" },
  "Kids": { iconName: "Baby", color: "#F0FFF4", hoverColor: "#22C55E" },
  "Sports": { iconName: "Trophy", color: "#FFF7F0", hoverColor: "#F97316" },
  "Formal": { iconName: "Briefcase", color: "#F8FAFC", hoverColor: "#64748B" },
  "Casual": { iconName: "Shirt", color: "#FFF5F0", hoverColor: "#F59E0B" },
};
